# Generated by Django 4.2.1 on 2023-05-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Womenswear', 'Womenswear'), ('Vehicles', 'Vehicles'), ('Sporting goods', 'Sporting goods')], max_length=20)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
